defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "frame"

include: ['_pages']
relative_permalinks: false
baseurl: "/PiWeb-Api"
links:
  configuration: "[Configuration](/PiWeb-Api/DataService/configuration/)"
images:
  warning: "![Warning](/PiWeb-Api/images/warning.png)"
  info: "![Warning](/PiWeb-Api/images/info.png)"
headers:
  example: "![Example](/PiWeb-Api/images/document-info.png) Example:"
  request: "![Request](/PiWeb-Api/images/server-import.png) Request"
  response: "![Response](/PiWeb-Api/images/server-export.png) Response"
sections:
  beginExampleWebService: "<fieldset><legend> Direct webservice call </legend>"
  beginExampleAPI: "<fieldset><legend> Webservice call via API.dll </legend>"
  endExample: "</fieldset>"
  endCode: "</div>"
settings:
  defaultCodeFormat: "json"
gems:
  - jekyll-redirect-from
