defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "frame"

include: ['_pages']
relative_permalinks: false
baseurl: "/PiWeb-Api"
links:
  configuration: "[Configuration](/PiWeb-Api/dataservice/configuration/)"
images:
  warning: "![Warning](/PiWeb-Api/images/warning.png)"
  info: "![Info](/PiWeb-Api/images/info.png)"
  summary: "![Info](/PiWeb-Api/images/summary.png)"
  list-info: "![List Info](/PiWeb-Api/images/list-info.png)"
  document-info: "![Document Info](/PiWeb-Api/images/document-info.png)"
  function-get: "![Get](/PiWeb-Api/images/function-get.png)"
  function-create: "![Create](/PiWeb-Api/images/function-create.png)"
  function-update: "![Update](/PiWeb-Api/images/function-update.png)"
  function-delete: "![Delete](/PiWeb-Api/images/function-delete.png)"
headers:
  example: "![Example](/PiWeb-Api/images/document-info.png) Example:"
  request: "![Request](/PiWeb-Api/images/server-import.png) Request"
  response: "![Response](/PiWeb-Api/images/server-export.png) Response"
sections:
  beginExampleWebService: "<fieldset><legend><span><img src=\"/PiWeb-Api/images/document-info.png\"/></span> Example:</legend>"
  beginExampleAPI: "<fieldset><legend> Webservice call via API.dll </legend>"
  endExample: "</fieldset>"
  endCode: "</div>"
settings:
  defaultCodeFormat: "json"
gems:
  - jekyll-redirect-from
