defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "frame"

include: ['_pages']
relative_permalinks: false
baseurl: "/PiWeb-Api"
links:
  configuration: "[Configuration](/PiWeb-Api/dataservice/configuration/)"
images:
  warning: "![Warning](/PiWeb-Api/images/warning.png)"
  info: "![Info](/PiWeb-Api/images/info.png)"
sections:
  getLabel: <span class="label label-primary">GET</span>
  postLabel: <span class="label label-success">POST</span>
  putLabel: <span class="label label-warning">PUT</span>
  deleteLabel: <span class="label label-danger">DELETE</span>
headers:
  example: "##### ![Example](/PiWeb-Api/images/document-info.png) Example: "
  request: "##### Request"
  response: "##### Response"
gems:
  - jekyll-redirect-from
